# Generated by Django 4.2.2 on 2023-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre'), ('webmaster', 'Webmaster'), ('stocker', 'Stocker')], default='Membre', max_length=10),
        ),
    ]
