# Generated by Django 4.2.2 on 2023-07-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image1', models.URLField()),
                ('image2', models.URLField()),
                ('image3', models.URLField()),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('U', 'Unisexe')], max_length=1)),
                ('description', models.TextField()),
                ('discount', models.IntegerField(choices=[(0, 'Pas de promo'), (25, '25% de réduction'), (40, '40% de réduction'), (50, '50% de réduction')], default=0)),
                ('stock38', models.IntegerField()),
                ('stock39', models.IntegerField()),
                ('stock40', models.IntegerField()),
                ('stock41', models.IntegerField()),
                ('stock42', models.IntegerField()),
                ('stock43', models.IntegerField()),
                ('stock44', models.IntegerField()),
                ('stock45', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
