# Generated by Django 4.2.2 on 2023-07-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_commentaryproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stock38',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock39',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock40',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock41',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock42',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock43',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock44',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock45',
        ),
    ]
